# Generated by Django 5.2.5 on 2025-09-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_hight',
            new_name='price_per_night',
        ),
    ]
