# Generated by Django 5.2.5 on 2025-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_rename_price_per_hight_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('simple', 'Простий'), ('comfort', 'Комфорт'), ('luxury', 'Люкс')], max_length=100),
        ),
    ]
